cursor #ecdfe5
cursor_text_color #d2c2cb

foreground            #ecdfe5
background            #181216
selection_foreground  #3e2a39
selection_background  #dbbed1
url_color             #f3b2e3
color0   #181216
color1   #d85b3c
color2   #6ed681
color3   #d1db7b
color4   #c75aaa
color5   #b68fac
color6   #f3b2e3
color7   #abb2bf
color8   #5c6370
color9   #e0785f
color10   #86e096
color11   #e0e897
color12   #ffbff4
color13   #b158a9
color14   #a8638d
color15   #ffffff
