# Shell Configuration
shell /usr/bin/fish

# Font Configuration
font_family      Fira Code Light
font_size 12.0

# Window Configuration
window_padding_width 8
background_blur 32
hide_window_decorations yes

# Cursor Configuration
cursor_shape beam

# Scrollback
scrollback_lines 3000

# Terminal features
strip_trailing_spaces smart
confirm_os_window_close 0

# Tab configuration
tab_bar_style powerline

# Shell intergration
shell_integration enabled

# Dank color generation
include dank-tabs.conf
include dank-theme.conf
